name: pocketkeeper
description: Final Year Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Library
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  google_fonts: ^2.3.3
  http: ^0.13.6

  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # App Icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_1024.png"
  min_sdk_android: 21
