name: pocketkeeper
description: "Final Year Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Library
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3
  filter_list: ^1.0.3
  date_picker_plus: ^3.0.2
  card_swiper: ^3.0.1
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  # table_calendar: ^3.0.9

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Notification
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^17.2.1+2

  # Image
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0

  # OCR
  camera: ^0.10.5+5
  cunning_document_scanner: ^1.2.3
  google_mlkit_entity_extraction: ^0.13.0
  google_mlkit_text_recognition: ^0.13.0

  # Google Sign In
  google_sign_in: ^6.2.1
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6

  # Database
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.3
  path: ^1.9.0

  shared_preferences: ^2.2.2

  # Check internet
  connectivity_plus: ^6.0.3

  # Open external link
  url_launcher: ^6.3.0

  # Biometric
  local_auth: ^2.2.0
  flutter_screen_lock: ^9.1.0

  # Backup
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_secure_storage: ^9.2.2
  external_path: ^1.0.3

  # Misc
  http: ^1.2.1
  intl: ^0.18.1
  google_generative_ai: ^0.4.3
  app_settings: ^5.1.1
  permission_handler: ^11.3.1
  currency_converter: ^2.0.0

dev_dependencies:
  # Local database
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
    - gen_ai_credential.json
