// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../app_setting.dart';
import '../category.dart';
import '../expense.dart';
import '../expense_goal.dart';
import '../expense_limit.dart';
import '../financial_blog.dart';
import '../goal_saving_record.dart';
import '../money_account.dart';
import '../notification.dart';
import '../role.dart';
import '../user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 999501084154178691),
      name: 'Accounts',
      lastPropertyId: const obx_int.IdUid(6, 1779489783762104047),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2535696463145739425),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5834541316193792738),
            name: 'accountName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1950126597901697312),
            name: 'accountIconHex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 287367284185907958),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6553148398328907603),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1779489783762104047),
            name: 'updatedDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7712490463443333360),
      name: 'AppSetting',
      lastPropertyId: const obx_int.IdUid(15, 5901909496239423032),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5549359506544979984),
            name: 'settingId',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6610796873858247419),
            name: 'appName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8385218562767138111),
            name: 'appVersion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4049961202379835073),
            name: 'appTheme',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9119072393749619836),
            name: 'appLanguage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4890182397345766885),
            name: 'currencyIndicator',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2269605152607752038),
            name: 'currencyCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5939213234496744406),
            name: 'isNotificationOn',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6054304317206566008),
            name: 'isGoogleSignIn',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6461716320413689158),
            name: 'isBiometricOn',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 9202230130797677318),
            name: 'lastBackupDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3354612531375176566),
            name: 'lastRestoreDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5965197001383577056),
            name: 'lastResyncDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5927323911257709116),
            name: 'monthlyLimit',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 5901909496239423032),
            name: 'endOfMonth',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2618232064163370990),
      name: 'Category',
      lastPropertyId: const obx_int.IdUid(8, 6627508791798241584),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7404973162188597184),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3629613608818171693),
            name: 'categoryName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2225517518839457166),
            name: 'categoryType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1569062679114502383),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5235247564191413064),
            name: 'iconHex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8042270252563851859),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 771888509712242318),
            name: 'updatedDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6627508791798241584),
            name: 'iconColor',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 8560269397521468160),
      name: 'ExpenseGoal',
      lastPropertyId: const obx_int.IdUid(11, 492044385367023248),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 24423709559089377),
            name: 'goalId',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6340471398746951331),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 651426744672100634),
            name: 'targetAmount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7846651831267819901),
            name: 'currentAmount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5888876791365642593),
            name: 'suggestedAmount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3510073384227276842),
            name: 'syncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4664542553946340451),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1498758849413288450),
            name: 'iconHex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1501559618512637110),
            name: 'dueDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2989735943758360689),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 492044385367023248),
            name: 'updatedDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4579103331409925191),
      name: 'ExpenseLimit',
      lastPropertyId: const obx_int.IdUid(7, 2951959170565059027),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2921590906096378195),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1701889841505990673),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8021338703085396596),
            name: 'syncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4198004205694566348),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5210514620709234847),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3989873985380674925),
            name: 'updatedDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2951959170565059027),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 1283344528150657201),
            relationTarget: 'Category')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 3388643883908189044),
      name: 'Expenses',
      lastPropertyId: const obx_int.IdUid(12, 3222087354243065890),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3413665927368853432),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6315142109644697428),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6755874128109026928),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7897650150200755893),
            name: 'expensesType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8053737325335813240),
            name: 'syncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 442274832185035386),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 395944563124336111),
            name: 'image',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8318126766105468633),
            name: 'expensesDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6595456591777040027),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 641322369110389805),
            name: 'updatedDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 85265032137587535),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 8888539687188911311),
            relationTarget: 'Category'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3222087354243065890),
            name: 'accountId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 8655281233167077820),
            relationTarget: 'Accounts')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 5254562440516345491),
      name: 'FinancialBlog',
      lastPropertyId: const obx_int.IdUid(10, 4906045951845775389),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5726122450292430397),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8089996526362285431),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8392351249864392703),
            name: 'author',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5301453352536332434),
            name: 'blogImage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 820560737596030937),
            name: 'authorImage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4480375860320752080),
            name: 'url',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3815077656769938795),
            name: 'averageReadingTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8134722284338362756),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6769655735012234788),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4906045951845775389),
            name: 'updatedDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 8643486749230335392),
      name: 'GoalSavingRecord',
      lastPropertyId: const obx_int.IdUid(8, 395703085863406540),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8704544214982286614),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5554897492523836337),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2714792608465399885),
            name: 'syncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3982145385275611986),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2257559202204757432),
            name: 'savingDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1810581142036640724),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4625627902019026251),
            name: 'updatedDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 395703085863406540),
            name: 'goalId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 6152306727790578652),
            relationTarget: 'ExpenseGoal')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 4793938487930377418),
      name: 'Notifications',
      lastPropertyId: const obx_int.IdUid(9, 8219600331282341137),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8019987984059912092),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 30817162659239832),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8759508719511383076),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8107860545739754183),
            name: 'notificationType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 501501133080825640),
            name: 'readStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5021352990786013962),
            name: 'syncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 865957853834208261),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1637932634905144054),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8219600331282341137),
            name: 'updatedDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 3225889351163727697),
      name: 'Role',
      lastPropertyId: const obx_int.IdUid(2, 2006472715619673711),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8349265506984174919),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2006472715619673711),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(11, 3303506105996232916),
      name: 'Users',
      lastPropertyId: const obx_int.IdUid(10, 6383910566730481225),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7908692662929945666),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2156724089252427296),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1694318780572984723),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4897972722041154841),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3615923665191619727),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8058656914223243498),
            name: 'discordId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2863843055139014738),
            name: 'profilePicture',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1812671948358794764),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 63286413589998657),
            name: 'updatedDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6383910566730481225),
            name: 'roleId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 1964695107453293705),
            relationTarget: 'Role')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(11, 3303506105996232916),
      lastIndexId: const obx_int.IdUid(5, 1964695107453293705),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Accounts: obx_int.EntityDefinition<Accounts>(
        model: _entities[0],
        toOneRelations: (Accounts object) => [],
        toManyRelations: (Accounts object) => {},
        getId: (Accounts object) => object.id,
        setId: (Accounts object, int id) {
          object.id = id;
        },
        objectToFB: (Accounts object, fb.Builder fbb) {
          final accountNameOffset = fbb.writeString(object.accountName);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, accountNameOffset);
          fbb.addInt64(2, object.accountIconHex);
          fbb.addInt64(3, object.status);
          fbb.addInt64(4, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final accountNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final statusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = Accounts(
              accountName: accountNameParam, status: statusParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..accountIconHex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));

          return object;
        }),
    AppSetting: obx_int.EntityDefinition<AppSetting>(
        model: _entities[1],
        toOneRelations: (AppSetting object) => [],
        toManyRelations: (AppSetting object) => {},
        getId: (AppSetting object) => object.settingId,
        setId: (AppSetting object, int id) {
          object.settingId = id;
        },
        objectToFB: (AppSetting object, fb.Builder fbb) {
          final appNameOffset = fbb.writeString(object.appName);
          final appVersionOffset = fbb.writeString(object.appVersion);
          final appThemeOffset = fbb.writeString(object.appTheme);
          final appLanguageOffset = fbb.writeString(object.appLanguage);
          final currencyIndicatorOffset =
              fbb.writeString(object.currencyIndicator);
          final currencyCodeOffset = fbb.writeString(object.currencyCode);
          fbb.startTable(16);
          fbb.addInt64(0, object.settingId);
          fbb.addOffset(1, appNameOffset);
          fbb.addOffset(2, appVersionOffset);
          fbb.addOffset(3, appThemeOffset);
          fbb.addOffset(4, appLanguageOffset);
          fbb.addOffset(5, currencyIndicatorOffset);
          fbb.addOffset(6, currencyCodeOffset);
          fbb.addBool(7, object.isNotificationOn);
          fbb.addBool(8, object.isGoogleSignIn);
          fbb.addBool(9, object.isBiometricOn);
          fbb.addInt64(10, object.lastBackupDate?.millisecondsSinceEpoch);
          fbb.addInt64(11, object.lastRestoreDate?.millisecondsSinceEpoch);
          fbb.addInt64(12, object.lastResyncDate?.millisecondsSinceEpoch);
          fbb.addFloat64(13, object.monthlyLimit);
          fbb.addInt64(14, object.endOfMonth);
          fbb.finish(fbb.endTable());
          return object.settingId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastBackupDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24);
          final lastRestoreDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final lastResyncDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final object = AppSetting()
            ..settingId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..appName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..appVersion = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..appTheme = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..appLanguage = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..currencyIndicator = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..currencyCode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..isNotificationOn =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false)
            ..isGoogleSignIn =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false)
            ..isBiometricOn =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false)
            ..lastBackupDate = lastBackupDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastBackupDateValue)
            ..lastRestoreDate = lastRestoreDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastRestoreDateValue)
            ..lastResyncDate = lastResyncDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastResyncDateValue)
            ..monthlyLimit =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 30, 0)
            ..endOfMonth =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);

          return object;
        }),
    Category: obx_int.EntityDefinition<Category>(
        model: _entities[2],
        toOneRelations: (Category object) => [],
        toManyRelations: (Category object) => {},
        getId: (Category object) => object.id,
        setId: (Category object, int id) {
          object.id = id;
        },
        objectToFB: (Category object, fb.Builder fbb) {
          final categoryNameOffset = fbb.writeString(object.categoryName);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryNameOffset);
          fbb.addInt64(2, object.categoryType);
          fbb.addInt64(3, object.status);
          fbb.addInt64(4, object.iconHex);
          fbb.addInt64(5, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedDate.millisecondsSinceEpoch);
          fbb.addInt64(7, object.iconColor);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Category()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..categoryName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..categoryType =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..iconHex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..iconColor =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);

          return object;
        }),
    ExpenseGoal: obx_int.EntityDefinition<ExpenseGoal>(
        model: _entities[3],
        toOneRelations: (ExpenseGoal object) => [],
        toManyRelations: (ExpenseGoal object) => {},
        getId: (ExpenseGoal object) => object.goalId,
        setId: (ExpenseGoal object, int id) {
          object.goalId = id;
        },
        objectToFB: (ExpenseGoal object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(12);
          fbb.addInt64(0, object.goalId);
          fbb.addOffset(1, descriptionOffset);
          fbb.addFloat64(2, object.targetAmount);
          fbb.addFloat64(3, object.currentAmount);
          fbb.addFloat64(4, object.suggestedAmount);
          fbb.addInt64(5, object.syncStatus);
          fbb.addInt64(6, object.status);
          fbb.addInt64(7, object.iconHex);
          fbb.addInt64(8, object.dueDate?.millisecondsSinceEpoch);
          fbb.addInt64(9, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(10, object.updatedDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.goalId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dueDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final dueDateParam = dueDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
          final object = ExpenseGoal(dueDate: dueDateParam)
            ..goalId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..targetAmount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..currentAmount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..suggestedAmount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..syncStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..iconHex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0));

          return object;
        }),
    ExpenseLimit: obx_int.EntityDefinition<ExpenseLimit>(
        model: _entities[4],
        toOneRelations: (ExpenseLimit object) => [object.category],
        toManyRelations: (ExpenseLimit object) => {},
        getId: (ExpenseLimit object) => object.id,
        setId: (ExpenseLimit object, int id) {
          object.id = id;
        },
        objectToFB: (ExpenseLimit object, fb.Builder fbb) {
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.amount);
          fbb.addInt64(2, object.syncStatus);
          fbb.addInt64(3, object.status);
          fbb.addInt64(4, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedDate.millisecondsSinceEpoch);
          fbb.addInt64(6, object.category.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ExpenseLimit()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..amount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..syncStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.category.attach(store);
          return object;
        }),
    Expenses: obx_int.EntityDefinition<Expenses>(
        model: _entities[5],
        toOneRelations: (Expenses object) => [object.category, object.account],
        toManyRelations: (Expenses object) => {},
        getId: (Expenses object) => object.id,
        setId: (Expenses object, int id) {
          object.id = id;
        },
        objectToFB: (Expenses object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          final imageOffset =
              object.image == null ? null : fbb.writeListInt8(object.image!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, descriptionOffset);
          fbb.addFloat64(2, object.amount);
          fbb.addInt64(3, object.expensesType);
          fbb.addInt64(4, object.syncStatus);
          fbb.addInt64(5, object.status);
          fbb.addOffset(6, imageOffset);
          fbb.addInt64(7, object.expensesDate.millisecondsSinceEpoch);
          fbb.addInt64(8, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedDate.millisecondsSinceEpoch);
          fbb.addInt64(10, object.category.targetId);
          fbb.addInt64(11, object.account.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Expenses()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..amount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..expensesType =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..syncStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..image = const fb.Uint8ListReader(lazy: false)
                .vTableGetNullable(buffer, rootOffset, 16) as Uint8List?
            ..expensesDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0))
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.category.attach(store);
          object.account.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          object.account.attach(store);
          return object;
        }),
    FinancialBlog: obx_int.EntityDefinition<FinancialBlog>(
        model: _entities[6],
        toOneRelations: (FinancialBlog object) => [],
        toManyRelations: (FinancialBlog object) => {},
        getId: (FinancialBlog object) => object.id,
        setId: (FinancialBlog object, int id) {
          object.id = id;
        },
        objectToFB: (FinancialBlog object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final authorOffset = fbb.writeString(object.author);
          final blogImageOffset = object.blogImage == null
              ? null
              : fbb.writeString(object.blogImage!);
          final authorImageOffset = object.authorImage == null
              ? null
              : fbb.writeString(object.authorImage!);
          final urlOffset =
              object.url == null ? null : fbb.writeString(object.url!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, authorOffset);
          fbb.addOffset(3, blogImageOffset);
          fbb.addOffset(4, authorImageOffset);
          fbb.addOffset(5, urlOffset);
          fbb.addInt64(6, object.averageReadingTime);
          fbb.addInt64(7, object.status);
          fbb.addInt64(8, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FinancialBlog()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..author = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..blogImage = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..authorImage = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..url = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..averageReadingTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));

          return object;
        }),
    GoalSavingRecord: obx_int.EntityDefinition<GoalSavingRecord>(
        model: _entities[7],
        toOneRelations: (GoalSavingRecord object) => [object.goal],
        toManyRelations: (GoalSavingRecord object) => {},
        getId: (GoalSavingRecord object) => object.id,
        setId: (GoalSavingRecord object, int id) {
          object.id = id;
        },
        objectToFB: (GoalSavingRecord object, fb.Builder fbb) {
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.amount);
          fbb.addInt64(2, object.syncStatus);
          fbb.addInt64(3, object.status);
          fbb.addInt64(4, object.savingDate.millisecondsSinceEpoch);
          fbb.addInt64(5, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedDate.millisecondsSinceEpoch);
          fbb.addInt64(7, object.goal.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = GoalSavingRecord()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..amount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..syncStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..savingDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          object.goal.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.goal.attach(store);
          return object;
        }),
    Notifications: obx_int.EntityDefinition<Notifications>(
        model: _entities[8],
        toOneRelations: (Notifications object) => [],
        toManyRelations: (Notifications object) => {},
        getId: (Notifications object) => object.id,
        setId: (Notifications object, int id) {
          object.id = id;
        },
        objectToFB: (Notifications object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.notificationType);
          fbb.addInt64(4, object.readStatus);
          fbb.addInt64(5, object.syncStatus);
          fbb.addInt64(6, object.status);
          fbb.addInt64(7, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Notifications()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..notificationType =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..readStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..syncStatus =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));

          return object;
        }),
    Role: obx_int.EntityDefinition<Role>(
        model: _entities[9],
        toOneRelations: (Role object) => [],
        toManyRelations: (Role object) => {},
        getId: (Role object) => object.id,
        setId: (Role object, int id) {
          object.id = id;
        },
        objectToFB: (Role object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Role()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '');

          return object;
        }),
    Users: obx_int.EntityDefinition<Users>(
        model: _entities[10],
        toOneRelations: (Users object) => [object.role],
        toManyRelations: (Users object) => {},
        getId: (Users object) => object.id,
        setId: (Users object, int id) {
          object.id = id;
        },
        objectToFB: (Users object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final emailOffset = fbb.writeString(object.email);
          final passwordOffset = fbb.writeString(object.password);
          final discordIdOffset = fbb.writeString(object.discordId);
          final profilePictureOffset = object.profilePicture == null
              ? null
              : fbb.writeListInt8(object.profilePicture!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.addInt64(4, object.status);
          fbb.addOffset(5, discordIdOffset);
          fbb.addOffset(6, profilePictureOffset);
          fbb.addInt64(7, object.createdDate.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedDate.millisecondsSinceEpoch);
          fbb.addInt64(9, object.role.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Users()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..password = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..status =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..discordId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..profilePicture = const fb.Uint8ListReader(lazy: false)
                .vTableGetNullable(buffer, rootOffset, 16) as Uint8List?
            ..createdDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0))
            ..updatedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          object.role.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.role.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Accounts] entity fields to define ObjectBox queries.
class Accounts_ {
  /// See [Accounts.id].
  static final id =
      obx.QueryIntegerProperty<Accounts>(_entities[0].properties[0]);

  /// See [Accounts.accountName].
  static final accountName =
      obx.QueryStringProperty<Accounts>(_entities[0].properties[1]);

  /// See [Accounts.accountIconHex].
  static final accountIconHex =
      obx.QueryIntegerProperty<Accounts>(_entities[0].properties[2]);

  /// See [Accounts.status].
  static final status =
      obx.QueryIntegerProperty<Accounts>(_entities[0].properties[3]);

  /// See [Accounts.createdDate].
  static final createdDate =
      obx.QueryDateProperty<Accounts>(_entities[0].properties[4]);

  /// See [Accounts.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<Accounts>(_entities[0].properties[5]);
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.settingId].
  static final settingId =
      obx.QueryIntegerProperty<AppSetting>(_entities[1].properties[0]);

  /// See [AppSetting.appName].
  static final appName =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[1]);

  /// See [AppSetting.appVersion].
  static final appVersion =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[2]);

  /// See [AppSetting.appTheme].
  static final appTheme =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[3]);

  /// See [AppSetting.appLanguage].
  static final appLanguage =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[4]);

  /// See [AppSetting.currencyIndicator].
  static final currencyIndicator =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[5]);

  /// See [AppSetting.currencyCode].
  static final currencyCode =
      obx.QueryStringProperty<AppSetting>(_entities[1].properties[6]);

  /// See [AppSetting.isNotificationOn].
  static final isNotificationOn =
      obx.QueryBooleanProperty<AppSetting>(_entities[1].properties[7]);

  /// See [AppSetting.isGoogleSignIn].
  static final isGoogleSignIn =
      obx.QueryBooleanProperty<AppSetting>(_entities[1].properties[8]);

  /// See [AppSetting.isBiometricOn].
  static final isBiometricOn =
      obx.QueryBooleanProperty<AppSetting>(_entities[1].properties[9]);

  /// See [AppSetting.lastBackupDate].
  static final lastBackupDate =
      obx.QueryDateProperty<AppSetting>(_entities[1].properties[10]);

  /// See [AppSetting.lastRestoreDate].
  static final lastRestoreDate =
      obx.QueryDateProperty<AppSetting>(_entities[1].properties[11]);

  /// See [AppSetting.lastResyncDate].
  static final lastResyncDate =
      obx.QueryDateProperty<AppSetting>(_entities[1].properties[12]);

  /// See [AppSetting.monthlyLimit].
  static final monthlyLimit =
      obx.QueryDoubleProperty<AppSetting>(_entities[1].properties[13]);

  /// See [AppSetting.endOfMonth].
  static final endOfMonth =
      obx.QueryIntegerProperty<AppSetting>(_entities[1].properties[14]);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[0]);

  /// See [Category.categoryName].
  static final categoryName =
      obx.QueryStringProperty<Category>(_entities[2].properties[1]);

  /// See [Category.categoryType].
  static final categoryType =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[2]);

  /// See [Category.status].
  static final status =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[3]);

  /// See [Category.iconHex].
  static final iconHex =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[4]);

  /// See [Category.createdDate].
  static final createdDate =
      obx.QueryDateProperty<Category>(_entities[2].properties[5]);

  /// See [Category.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<Category>(_entities[2].properties[6]);

  /// See [Category.iconColor].
  static final iconColor =
      obx.QueryIntegerProperty<Category>(_entities[2].properties[7]);
}

/// [ExpenseGoal] entity fields to define ObjectBox queries.
class ExpenseGoal_ {
  /// See [ExpenseGoal.goalId].
  static final goalId =
      obx.QueryIntegerProperty<ExpenseGoal>(_entities[3].properties[0]);

  /// See [ExpenseGoal.description].
  static final description =
      obx.QueryStringProperty<ExpenseGoal>(_entities[3].properties[1]);

  /// See [ExpenseGoal.targetAmount].
  static final targetAmount =
      obx.QueryDoubleProperty<ExpenseGoal>(_entities[3].properties[2]);

  /// See [ExpenseGoal.currentAmount].
  static final currentAmount =
      obx.QueryDoubleProperty<ExpenseGoal>(_entities[3].properties[3]);

  /// See [ExpenseGoal.suggestedAmount].
  static final suggestedAmount =
      obx.QueryDoubleProperty<ExpenseGoal>(_entities[3].properties[4]);

  /// See [ExpenseGoal.syncStatus].
  static final syncStatus =
      obx.QueryIntegerProperty<ExpenseGoal>(_entities[3].properties[5]);

  /// See [ExpenseGoal.status].
  static final status =
      obx.QueryIntegerProperty<ExpenseGoal>(_entities[3].properties[6]);

  /// See [ExpenseGoal.iconHex].
  static final iconHex =
      obx.QueryIntegerProperty<ExpenseGoal>(_entities[3].properties[7]);

  /// See [ExpenseGoal.dueDate].
  static final dueDate =
      obx.QueryDateProperty<ExpenseGoal>(_entities[3].properties[8]);

  /// See [ExpenseGoal.createdDate].
  static final createdDate =
      obx.QueryDateProperty<ExpenseGoal>(_entities[3].properties[9]);

  /// See [ExpenseGoal.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<ExpenseGoal>(_entities[3].properties[10]);
}

/// [ExpenseLimit] entity fields to define ObjectBox queries.
class ExpenseLimit_ {
  /// See [ExpenseLimit.id].
  static final id =
      obx.QueryIntegerProperty<ExpenseLimit>(_entities[4].properties[0]);

  /// See [ExpenseLimit.amount].
  static final amount =
      obx.QueryDoubleProperty<ExpenseLimit>(_entities[4].properties[1]);

  /// See [ExpenseLimit.syncStatus].
  static final syncStatus =
      obx.QueryIntegerProperty<ExpenseLimit>(_entities[4].properties[2]);

  /// See [ExpenseLimit.status].
  static final status =
      obx.QueryIntegerProperty<ExpenseLimit>(_entities[4].properties[3]);

  /// See [ExpenseLimit.createdDate].
  static final createdDate =
      obx.QueryDateProperty<ExpenseLimit>(_entities[4].properties[4]);

  /// See [ExpenseLimit.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<ExpenseLimit>(_entities[4].properties[5]);

  /// See [ExpenseLimit.category].
  static final category = obx.QueryRelationToOne<ExpenseLimit, Category>(
      _entities[4].properties[6]);
}

/// [Expenses] entity fields to define ObjectBox queries.
class Expenses_ {
  /// See [Expenses.id].
  static final id =
      obx.QueryIntegerProperty<Expenses>(_entities[5].properties[0]);

  /// See [Expenses.description].
  static final description =
      obx.QueryStringProperty<Expenses>(_entities[5].properties[1]);

  /// See [Expenses.amount].
  static final amount =
      obx.QueryDoubleProperty<Expenses>(_entities[5].properties[2]);

  /// See [Expenses.expensesType].
  static final expensesType =
      obx.QueryIntegerProperty<Expenses>(_entities[5].properties[3]);

  /// See [Expenses.syncStatus].
  static final syncStatus =
      obx.QueryIntegerProperty<Expenses>(_entities[5].properties[4]);

  /// See [Expenses.status].
  static final status =
      obx.QueryIntegerProperty<Expenses>(_entities[5].properties[5]);

  /// See [Expenses.image].
  static final image =
      obx.QueryByteVectorProperty<Expenses>(_entities[5].properties[6]);

  /// See [Expenses.expensesDate].
  static final expensesDate =
      obx.QueryDateProperty<Expenses>(_entities[5].properties[7]);

  /// See [Expenses.createdDate].
  static final createdDate =
      obx.QueryDateProperty<Expenses>(_entities[5].properties[8]);

  /// See [Expenses.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<Expenses>(_entities[5].properties[9]);

  /// See [Expenses.category].
  static final category =
      obx.QueryRelationToOne<Expenses, Category>(_entities[5].properties[10]);

  /// See [Expenses.account].
  static final account =
      obx.QueryRelationToOne<Expenses, Accounts>(_entities[5].properties[11]);
}

/// [FinancialBlog] entity fields to define ObjectBox queries.
class FinancialBlog_ {
  /// See [FinancialBlog.id].
  static final id =
      obx.QueryIntegerProperty<FinancialBlog>(_entities[6].properties[0]);

  /// See [FinancialBlog.title].
  static final title =
      obx.QueryStringProperty<FinancialBlog>(_entities[6].properties[1]);

  /// See [FinancialBlog.author].
  static final author =
      obx.QueryStringProperty<FinancialBlog>(_entities[6].properties[2]);

  /// See [FinancialBlog.blogImage].
  static final blogImage =
      obx.QueryStringProperty<FinancialBlog>(_entities[6].properties[3]);

  /// See [FinancialBlog.authorImage].
  static final authorImage =
      obx.QueryStringProperty<FinancialBlog>(_entities[6].properties[4]);

  /// See [FinancialBlog.url].
  static final url =
      obx.QueryStringProperty<FinancialBlog>(_entities[6].properties[5]);

  /// See [FinancialBlog.averageReadingTime].
  static final averageReadingTime =
      obx.QueryIntegerProperty<FinancialBlog>(_entities[6].properties[6]);

  /// See [FinancialBlog.status].
  static final status =
      obx.QueryIntegerProperty<FinancialBlog>(_entities[6].properties[7]);

  /// See [FinancialBlog.createdDate].
  static final createdDate =
      obx.QueryDateProperty<FinancialBlog>(_entities[6].properties[8]);

  /// See [FinancialBlog.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<FinancialBlog>(_entities[6].properties[9]);
}

/// [GoalSavingRecord] entity fields to define ObjectBox queries.
class GoalSavingRecord_ {
  /// See [GoalSavingRecord.id].
  static final id =
      obx.QueryIntegerProperty<GoalSavingRecord>(_entities[7].properties[0]);

  /// See [GoalSavingRecord.amount].
  static final amount =
      obx.QueryDoubleProperty<GoalSavingRecord>(_entities[7].properties[1]);

  /// See [GoalSavingRecord.syncStatus].
  static final syncStatus =
      obx.QueryIntegerProperty<GoalSavingRecord>(_entities[7].properties[2]);

  /// See [GoalSavingRecord.status].
  static final status =
      obx.QueryIntegerProperty<GoalSavingRecord>(_entities[7].properties[3]);

  /// See [GoalSavingRecord.savingDate].
  static final savingDate =
      obx.QueryDateProperty<GoalSavingRecord>(_entities[7].properties[4]);

  /// See [GoalSavingRecord.createdDate].
  static final createdDate =
      obx.QueryDateProperty<GoalSavingRecord>(_entities[7].properties[5]);

  /// See [GoalSavingRecord.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<GoalSavingRecord>(_entities[7].properties[6]);

  /// See [GoalSavingRecord.goal].
  static final goal = obx.QueryRelationToOne<GoalSavingRecord, ExpenseGoal>(
      _entities[7].properties[7]);
}

/// [Notifications] entity fields to define ObjectBox queries.
class Notifications_ {
  /// See [Notifications.id].
  static final id =
      obx.QueryIntegerProperty<Notifications>(_entities[8].properties[0]);

  /// See [Notifications.title].
  static final title =
      obx.QueryStringProperty<Notifications>(_entities[8].properties[1]);

  /// See [Notifications.description].
  static final description =
      obx.QueryStringProperty<Notifications>(_entities[8].properties[2]);

  /// See [Notifications.notificationType].
  static final notificationType =
      obx.QueryIntegerProperty<Notifications>(_entities[8].properties[3]);

  /// See [Notifications.readStatus].
  static final readStatus =
      obx.QueryIntegerProperty<Notifications>(_entities[8].properties[4]);

  /// See [Notifications.syncStatus].
  static final syncStatus =
      obx.QueryIntegerProperty<Notifications>(_entities[8].properties[5]);

  /// See [Notifications.status].
  static final status =
      obx.QueryIntegerProperty<Notifications>(_entities[8].properties[6]);

  /// See [Notifications.createdDate].
  static final createdDate =
      obx.QueryDateProperty<Notifications>(_entities[8].properties[7]);

  /// See [Notifications.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<Notifications>(_entities[8].properties[8]);
}

/// [Role] entity fields to define ObjectBox queries.
class Role_ {
  /// See [Role.id].
  static final id = obx.QueryIntegerProperty<Role>(_entities[9].properties[0]);

  /// See [Role.name].
  static final name = obx.QueryStringProperty<Role>(_entities[9].properties[1]);
}

/// [Users] entity fields to define ObjectBox queries.
class Users_ {
  /// See [Users.id].
  static final id =
      obx.QueryIntegerProperty<Users>(_entities[10].properties[0]);

  /// See [Users.name].
  static final name =
      obx.QueryStringProperty<Users>(_entities[10].properties[1]);

  /// See [Users.email].
  static final email =
      obx.QueryStringProperty<Users>(_entities[10].properties[2]);

  /// See [Users.password].
  static final password =
      obx.QueryStringProperty<Users>(_entities[10].properties[3]);

  /// See [Users.status].
  static final status =
      obx.QueryIntegerProperty<Users>(_entities[10].properties[4]);

  /// See [Users.discordId].
  static final discordId =
      obx.QueryStringProperty<Users>(_entities[10].properties[5]);

  /// See [Users.profilePicture].
  static final profilePicture =
      obx.QueryByteVectorProperty<Users>(_entities[10].properties[6]);

  /// See [Users.createdDate].
  static final createdDate =
      obx.QueryDateProperty<Users>(_entities[10].properties[7]);

  /// See [Users.updatedDate].
  static final updatedDate =
      obx.QueryDateProperty<Users>(_entities[10].properties[8]);

  /// See [Users.role].
  static final role =
      obx.QueryRelationToOne<Users, Role>(_entities[10].properties[9]);
}
